version: '3.8'
services:
  playwright-test:
    image: playwright-test
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: npx playwright test uiComponents.spec.ts --project=chromium --grep '@smoke|@sanity'
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results